export const FETCH_USERSTORIES_REQUEST = "FETCH_USERSTORIES_REQUEST";
export const FETCH_USERSTORIES_SUCCESS = "FETCH_USERSTORIES_SUCCESS ";
export const FETCH_USERSTORIES_FAILED = "FETCH_USERSTORIES_FAILED";
export const FETCH_COLUMNS_REQUEST = "FETCH_COLUMNS_REQUEST";
export const FETCH_COLUMNS_SUCCESS = "FETCH_COLUMNS_SUCCESS ";
export const FETCH_COLUMNS_FAILED = "FETCH_COLUMNS_FAILED";
export const FETCH_SPRINTS_REQUEST = "FETCH_SPRINTS_REQUEST";
export const FETCH_SPRINTS_SUCCESS = "FETCH_SPRINTS_SUCCESS ";
export const FETCH_SPRINTS_FAILED = "FETCH_SPRINTS_FAILED";
export const FETCH_MEMBERSPRINTS_REQUEST = "FETCH_MEMBERSPRINTS_REQUEST";
export const FETCH_MEMBERSPRINTS_SUCCESS = "FETCH_MEMBERSPRINTS_SUCCESS ";
export const FETCH_MEMBERSPRINTS_FAILED = "FETCH_MEMBERSPRINTS_FAILED";
export const FETCH_MEMBERSPRINTSRATE_REQUEST =
  "FETCH_MEMBERSPRINTSRaATE_REQUEST";
export const FETCH_MEMBERSPRINTSRATE_SUCCESS =
  "FETCH_MEMBERSPRINTSRATE_SUCCESS ";
export const FETCH_MEMBERSPRINTSRATE_FAILED = "FETCH_MEMBERSPRINTSRATE_FAILED";
