export const FETCH_USERSTORIES_REQUEST = "FETCH_USERSTORIES_REQUEST";
export const FETCH_USERSTORIES_SUCCESS = "FETCH_USERSTORIES_SUCCESS ";
export const FETCH_USERSTORIES_FAILED = "FETCH_USERSTORIES_FAILED";
export const FETCH_COLUMNS_REQUEST = "FETCH_COLUMNS_REQUEST";
export const FETCH_COLUMNS_SUCCESS = "FETCH_COLUMNS_SUCCESS ";
export const FETCH_COLUMNS_FAILED = "FETCH_COLUMNS_FAILED";
export const FETCH_SPRINTS_REQUEST = "FETCH_SPRINTS_REQUEST";
export const FETCH_SPRINTS_SUCCESS = "FETCH_SPRINTS_SUCCESS ";
export const FETCH_SPRINTS_FAILED = "FETCH_SPRINTS_FAILED";
export const FETCH_MEMBERSPRINTS_REQUEST = "FETCH_MEMBERSPRINTS_REQUEST";
export const FETCH_MEMBERSPRINTS_SUCCESS = "FETCH_MEMBERSPRINTS_SUCCESS ";
export const FETCH_MEMBERSPRINTS_FAILED = "FETCH_MEMBERSPRINTS_FAILED";
export const FETCH_MEMBERSPRINTSRATE_REQUEST ="FETCH_MEMBERSPRINTSRaATE_REQUEST";
export const FETCH_MEMBERSPRINTSRATE_SUCCESS ="FETCH_MEMBERSPRINTSRATE_SUCCESS ";
export const FETCH_MEMBERSPRINTSRATE_FAILED = "FETCH_MEMBERSPRINTSRATE_FAILED";
export const UPDATE_RATEMEMBER_REQUEST ="UPDATE_RATEMEMBER_REQUEST";
export const UPDATE_RATEMEMBER_SUCCESS ="UPDATE_RATEMEMBER_SUCCESS ";
export const UPDATE_RATEMEMBER_FAILED = "UPDATE_RATEMEMBER_FAILED";

export const FETCH_ABSENCE_REQUEST ="FETCH_ABSENCE_REQUEST";
export const FETCH_ABSENCE_SUCCESS ="FETCH_ABSENCE_SUCCESS ";
export const FETCH_ABSENCE_FAILED = "FETCH_ABSENCE_FAILED";

export const FETCH_WORKDONE_REQUEST ="FETCH_WORKDONE_REQUEST";
export const FETCH_WORKDONE_SUCCESS ="FETCH_WORKDONE_SUCCESS ";
export const FETCH_WORKDONE_FAILED = "FETCH_WORKDONE_FAILED";

export const UPDATE_ETAT_REQUEST ="UPDATE_ETAT_REQUEST";
export const UPDATE_ETAT_SUCCESS ="UPDATE_ETAT_SUCCESS ";
export const UPDATE_ETAT_FAILED = "UPDATE_ETAT_FAILED";


export const RESET_STORE="RESET_STORE";